apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-rm342829
  namespace: rm342829
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grupo10-blog-site
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
