apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example
  namespace: rm342829
spec:
  rules:
    - host: grupo10-blog-site-rm342829.apps.na46a.prod.ole.redhat.com
      http:
        paths:
          - path: /
            backend:
              serviceName: grupo10-blog-site
              servicePort: 80
